version: "3"
services:
  presto-coordinator:
    container_name: prestroid-coordinator
    image: jkok005/prestroid-coordinator:latest
    ports:
      - "8080:8080"

  presto-worker:
    image: jkok005/prestroid-worker:latest  
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 40G